stages:
  - deploy

deploy:
  stage: deploy
  image: gitlab.praktikum-services.ru:5050/std-012-056/sausage-store/alpine/k8s:1.24.12
  only:
    changes:
      - sausage-store-chart/**/*
  script:
    - cd sausage-store-chart
    - mkdir ~/.kube
    - echo ${kubeconfig} | base64 -d > ~/.kube/config
    - helm repo add nexus $NEXUS_HELM_REPO --username $NEXUS_REPO_USER --password $NEXUS_REPO_PASS
    - helm repo update
    - helm upgrade --install sausage-store nexus/sausage-store
    - rm ~/.kube/config





