stages:
  - deploy

deploy:
  stage: deploy
  image: gitlab.praktikum-services.ru:5050/std-012-056/sausage-store/alpine/k8s:1.24.12
  only:
    changes:
      - sausage-store-chart/**/*
  script:
    - mkdir ~/.kube
    - echo ${kubeconfig} | base64 -d > ~/.kube/config
    - cd sausage-store-chart
    - helm package ./
    - pwd
    - ls -lah
    - curl -u std-012-056:4ay9U6W2 https://nexus.k8s.praktikum-services.tech/repository/sausage-store-helm-artamokhin-aleksandr-12/ --upload-file sausage-store-0.1.0.tgz
    - helm repo add nexus $NEXUS_HELM_REPO --username $NEXUS_REPO_USER --password $NEXUS_REPO_PASS
    - helm repo update
    - helm upgrade --install --set environment=test --atomic --timeout 15m sausage-store nexus/sausage-store
    - rm ~/.kube/config





