stages:
  - build

build:
  stage: build
  image: gitlab.praktikum-services.ru:5050/std-012-056/sausage-store/alpine/k8s:1.24.12
  only:
    changes:
      - kubernetes/*/*
  script:
    - cd kubernetes
    - mkdir ~/.kube
    - echo ${kubeconfig} | base64 -d > ~/.kube/config
    - kubectl apply -f backend
    - kubectl apply -f backend-report
    - kubectl apply -f frontend
    - rm ~/.kube/config




