# values.yaml
backend: # Это имя чарта из dependencies
  # Вместо latest правильнее использовать версию .Chart.AppVersion в шаблоне
  image: gitlab.praktikum-services.ru:5050/std-012-056/sausage-store/sausage-backend
  tag: latest
  replicas: 1
  resources:
    requests:
      memory: "125Mi"
      cpu: 0.1
    limits:
      memory: "250Mi"
      cpu: 0.2
  vault_IP: 158.160.34.207
  environment: production

backend-report:
  image: gitlab.praktikum-services.ru:5050/std-012-056/sausage-store/sausage-report
  tag: latest
  replicas: 1
  resources:
    requests:
      memory: "125Mi"
      cpu: 0.1
    limits:
      memory: "250Mi"
      cpu: 0.2
  environment: production

frontend:
  image: gitlab.praktikum-services.ru:5050/std-012-056/sausage-store/sausage-nginx
  tag: latest
  replicas: 1
  ingresshost: "artamokhin-aleksandr-12.k8s.praktikum-services.tech"
  resources:
    requests:
      memory: "125Mi"
      cpu: 0.1
    limits:
      memory: "250Mi"
      cpu: 0.2
  environment: production

yandex_cloud_services:
  # Пример значений для сервиса Managed PostgreSQL
  - service: managed-postgresql
    serviceId: c9qlet4gbg81d79211dr
    folderId: b1g6kb8sqccdk2sg5drr
    bearer_token: aje8084amokekkq7cbfh
    scrape_interval: 60s
  # Пример значений для сервиса Managed MongoDB
  - service: managed-mongodb
    serviceId: cakvctgrte4hunhvs8f
    folderId: b1g2hqnugteh52j2dfr
    bearer_token: AQVN3veeVseTVUm4RFjy-WRt9INXbdkS6Q8iC3Bh
    scrape_interval: 60s