---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sausage-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    meta.helm.sh/release-name: sausage
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: sausage-backend-report
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/component: backend-report
    app.kubernetes.io/part-of: sausage-store
    env: "{{ .Values.environment }}"

spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 15
  # Стратегия развёртывания. Recreate — удалит сначала все старые Pod'ы
  # Есть и более гибкая стратегии, например, RollingUpdate, которая будет обновлять Pod'ы порциями
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: backend-report
  template:
    metadata:
      labels:
        app: backend-report
    spec:
      containers:
        - name: backend-report
          image: "{{ .Values.image }}:{{.Values.tag }}"
          imagePullPolicy: Always
          resources:
{{ toYaml .Values.resources | indent 12}}
          env:
            - name: DB
              valueFrom:
                secretKeyRef:
                  name: mongo
                  key: mongodb
          ports:
            - name: backend-report
              containerPort: 8080
      imagePullSecrets:
        - name: docker-config-secret

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-report-hpa
  labels:
    app: backend-report-hpa
spec:
  minReplicas: 1
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-report
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
