# Секрет, необходимый, чтобы получить креды для БД:
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo
  annotations:
    meta.helm.sh/release-name: sausage
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app: mongo
data:
  mongodb: bW9uZ29kYjovL2FydGFtb2toaW4xOkRldm9wczEyMyFAcmMxYS1mdHNxODJ1b2w0dDdtY29xLm1kYi55YW5kZXhjbG91ZC5uZXQ6MjcwMTgvYXJ0YW1va2hpbjE/dGxzPXRydWUmdGxzQWxsb3dJbnZhbGlkQ2VydGlmaWNhdGVzPXRydWU=
type: Opaque
