- name: Копируем описание службы
  become: true
  template:
    src: /home/student/sausage-store-backend.service
    dest: /etc/systemd/system/sausage-store-backend.service

- name: Перечитываем конфигурацию systemd
  become: true
  systemd:
    daemon_reload: yes
    name: sausage-store-backend.service
