# Секрет, необходимый, чтобы соединяться с Vault и получать креды для БД:
---
apiVersion: v1
kind: Secret
metadata:
  name: vault
  annotations:
    meta.helm.sh/release-name: sausage
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app: vault
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  vault_token: ***REMOVED***
type: Opaque