# Секрет, необходимый, чтобы соединяться с Vault и получать креды для БД:
---
apiVersion: v1
kind: Secret
metadata:
  name: vault
  labels:
    app: vault
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  vault_token: ***REMOVED***
type: Opaque

# Секрет, необходимый, чтобы взаимодействовать с Docker Registry в GitLab:
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
  annotations:
    meta.helm.sh/release-name: sausage
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  .dockerconfigjson: >-
    ***REMOVED***
type: kubernetes.io/dockerconfigjson