# Секрет, необходимый, чтобы получить креды для БД:
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo
  labels:
    app: mongo
data:
  mongodb: bW9uZ29kYjovL2FydGFtb2toaW4xOkRldm9wczEyMyFAcmMxYS1mdHNxODJ1b2w0dDdtY29xLm1kYi55YW5kZXhjbG91ZC5uZXQ6MjcwMTgvYXJ0YW1va2hpbjE/dGxzPXRydWUmdGxzQWxsb3dJbnZhbGlkQ2VydGlmaWNhdGVzPXRydWU=
type: Opaque

# Секрет, необходимый, чтобы взаимодействовать с Docker Registry в GitLab:
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogIlpYSmhhMmh0WlhSNmVXRnViM1k2TlZrNWNESnlSM05RUVcxSFVIST0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson