---
apiVersion: v1
kind: Service
metadata:
  name: report
  labels:
   app: report
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: report