---
apiVersion: v1
kind: Service
metadata:
   name: report
   labels:
     app: report
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: report