{
 "title": "Sausage Store Infrastructure",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Использования CPU MongoDB",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "load_avg_1min{job=\"yandex_service_managed-mongodb\"}"
    }
   ]
  },
  {
   "title": "Использования CPU PostgreSQL",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "load_avg_1min{job=\"yandex_service_managed-postgresql\"}"
    }
   ]
  },
  {
   "title": "Использования RAM MongoDB",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(mem_used_bytes{job=\"yandex_service_managed-mongodb\"})/sum(mem_total_bytes{job=\"yandex_service_managed-mongodb\"})*100"
    }
   ]
  },
  {
   "title": "Использования RAM PostgreSQL",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum(mem_used_bytes{job=\"yandex_service_managed-postgresql\"})/sum(mem_total_bytes{job=\"yandex_service_managed-postgresql\"})*100"
    }
   ]
  },
  {
   "title": "Время обработки запросов MongoDB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "server_status_admin_opLatencies_reads_latency_rate"
    }
   ]
  },
  {
   "title": "Время обработки запросов PostgreSQL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "pooler_query_0_95_artamokhin1_artamokhin1"
    }
   ]
  }
 ]
}