{
 "title": "Sausage Store App",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "график насыщения — общее использование памяти",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes)*100/sum(jvm_memory_max_bytes)"
    }
   ]
  },
  {
   "title": "Задержка обработки запросов к URL /api/orders",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \r\n  rate(http_server_requests_seconds_bucket{uri=\"/api/orders\"}[1m])\r\n) "
    }
   ]
  },
  {
   "title": "Частота ошибок обращения к бизнес-эндпоинтам бэкенда в секунду",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{status=\"404\"}[1m])"
    }
   ]
  },
  {
   "title": "Трафик успешных запросов в секунду к бизнес-эндпоинтам бэкенда",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{method=\"GET\",status!~\"4..\",uri!=\"/actuator/prometheus\",uri!=\"/actuator/health\"}[1m])"
    }
   ]
  }
 ]
}