{
 "title": "Sausage Store Business",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sausage_type",
    "label": "sausage_type",
    "query": {
     "query": "label_values(sausage_orders_total, type)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Sausages Trends",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(sausage_orders_total{type=\"$sausage_type\"}[1m])"
    }
   ]
  },
  {
   "title": "Особая",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "rate(sausage_orders_total{type=\"Особая\"}[1m])"
    }
   ]
  },
  {
   "title": "Русская",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "rate(sausage_orders_total{type=\"Русская\"}[1m])"
    }
   ]
  },
  {
   "title": "Молочная",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(sausage_orders_total{type=\"Молочная\"}[1m])"
    }
   ]
  },
  {
   "title": "Сливочная",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "rate(sausage_orders_total{type=\"Сливочная\"}[1m])"
    }
   ]
  },
  {
   "title": "Мюнхенская",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "rate(sausage_orders_total{type=\"Мюнхенская\"}[1m])"
    }
   ]
  },
  {
   "title": "Нюренбергская",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(sausage_orders_total{type=\"Нюренбергская\"}[1m])"
    }
   ]
  }
 ]
}